{% set name = "mpltoolbox" %}
{% set version = "24.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mpltoolbox-{{ version }}.tar.gz
  sha256: 13c0b01881f5c5bb85145fbb52eab96b5b0cc08167b49cd969643c02f1e54ccf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numpy

test:
  imports:
    - mpltoolbox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mpltoolbox/mpltoolbox
  summary: Interactive tools for matplotlib
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nvaytet
