schema_version: 1

context:
  name: mpltoolbox
  version: "26.2.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/mpltoolbox-${{ version }}.tar.gz
  sha256: b8a600b35f1efe67a9ae4004cf75e15a33a2c281b12dbb55d155191f834aac1f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=77
    - setuptools-scm >=8.0
  run:
    - python >=${{ python_min }}
    - matplotlib-base
    - numpy

tests:
  - python:
      imports:
        - mpltoolbox
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Interactive tools for matplotlib
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/mpltoolbox/mpltoolbox
  homepage: https://scipp.github.io/mpltoolbox/

extra:
  recipe-maintainers:
    - conda-forge/scipp
